export { BoardFirstShell } from './BoardFirstShell';
export { WAVE1R_SYNTHETIC_ACTIVITY, WAVE1R_SYNTHETIC_CONTEXT } from './fixtures';
export {
  createBoardFirstActionActivityItem,
  createBoardFirstActionProposal,
  createBoardFirstAssignmentActivityItem,
  createBoardFirstAssignmentProposal,
  eligibleAssignmentSections,
  initialBoardFirstAssistantState,
  listBoardFirstCrewOptions,
  projectBoardFirstActivity,
  projectBoardFirstBoard,
  projectBoardFirstCaptureReceiptActivity,
  projectBoardFirstUnit,
  projectBoardFirstUnitActivity,
  projectBoardFirstUnitAttentions,
  reduceBoardFirstAssistant,
  selectBoardFirstSectionActions,
} from './projections';
export {
  BOARD_FIRST_HOST_DESTINATIONS,
  BOARD_FIRST_NAVIGATION,
  DEFAULT_BOARD_FIRST_VIEW,
} from './types';
export type {
  BoardFirstActionProposal,
  BoardFirstActivityItem,
  BoardFirstAssignmentProposal,
  BoardFirstAssistantAction,
  BoardFirstAssistantState,
  BoardFirstCaptureHandler,
  BoardFirstCaptureKind,
  BoardFirstCaptureReceipt,
  BoardFirstCaptureRequest,
  BoardFirstHostDestination,
  BoardFirstHostNavigationHandler,
  BoardFirstHostNavigationReceipt,
  BoardFirstHostNavigationRequest,
  BoardFirstReturnFocus,
  BoardFirstSectionAction,
  BoardFirstShellProps,
  BoardFirstTradeProjection,
  BoardFirstUnitProjection,
  BoardFirstView,
} from './types';
