// Pay-week packet PDF — the sheet Los hands Tony instead of dictating room
// by room for two hours. Rendered from the SAME per-crew packet data the
// on-screen "Pay week — for the board / Tony" summary shows (one source of
// truth: buildAllCrewPayroll, deduped per crew+room+round), so the paper,
// the screen, and the receipts can never disagree.

export interface PayPacketPdfCrew {
  readonly name: string;
  readonly trade: string; // 'Paint' | 'Clean'
  readonly headline: string; // e.g. "12 full · 4 touch-up · 3 cut-in"
  readonly beds: number;
  readonly commons: number;
  readonly rooms: readonly string[]; // formatted unit lines, lowest unit first
  readonly changeOrders: readonly string[];
  readonly textures: readonly string[];
}

export interface PayPacketPdfInput {
  readonly propertyName: string;
  readonly supervisor: string;
  readonly weekStart: string; // Sunday, YYYY-MM-DD
  readonly paintTotalsLine: string; // "31 full · 12 touch-up · 9 cut-in" ('' when none)
  readonly cleanTotal: number;
  readonly changeOrderTotal: number;
  readonly textureTotal: number;
  readonly crews: readonly PayPacketPdfCrew[];
  readonly cutIns: readonly string[]; // "1007 B (Blue Crew)"
}

export async function savePayWeekPacketPdf(input: PayPacketPdfInput): Promise<string> {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ format: 'a4', unit: 'mm' });
  const left = 18;
  const right = 192;
  let y = 22;

  const ensureRoom = (needed: number) => {
    if (y + needed <= 278) return;
    doc.addPage();
    y = 22;
  };
  const heading = (text: string) => {
    ensureRoom(14);
    y += 6;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text(text, left, y);
    y += 2;
    doc.setDrawColor(180);
    doc.line(left, y, right, y);
    y += 6;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10.5);
  };
  const line = (text: string, indent = 0) => {
    const wrapped = doc.splitTextToSize(text, right - left - indent) as string[];
    for (const part of wrapped) {
      ensureRoom(6);
      doc.text(part, left + indent, y);
      y += 5.5;
    }
  };

  const start = new Date(`${input.weekStart}T12:00:00`);
  const end = new Date(start);
  end.setDate(start.getDate() + 6);
  const fmt = (date: Date) => date.toLocaleDateString([], { day: 'numeric', month: 'short' });

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(17);
  doc.text(`${input.propertyName} — Pay Week Packet`, left, y);
  y += 8;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.text(
    `Week ${fmt(start)} – ${fmt(end)} (Sun–Sat) · Supervisor: ${input.supervisor}`,
    left,
    y,
  );
  y += 4;

  heading('Week totals');
  line(`Paint: ${input.paintTotalsLine || '—'}`);
  line(`Clean: ${input.cleanTotal} room${input.cleanTotal === 1 ? '' : 's'}`);
  line(`Change orders: ${input.changeOrderTotal} · Texture repairs: ${input.textureTotal}`);
  line('Counts are rooms crews reported done, deduped per crew, room, and round. A full+cut-in counts as a full AND a cut-in, so paint task totals overlap on purpose.');

  for (const crew of input.crews) {
    heading(`${crew.name} (${crew.trade}) — ${crew.headline} · ${crew.beds} beds · ${crew.commons} common`);
    for (const room of crew.rooms) line(room, 4);
    for (const order of crew.changeOrders) line(`CHANGE ORDER — ${order}`, 4);
    for (const texture of crew.textures) line(`TEXTURE — ${texture}`, 4);
  }

  heading(`Cut-in rooms, tracked separately · ${input.cutIns.length}`);
  line(input.cutIns.length > 0 ? input.cutIns.join(', ') : 'None this week.');

  ensureRoom(16);
  y += 8;
  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text(
    'Personal record generated by Turn OS. The paper TurnBoard remains the official approval record.',
    left,
    y,
  );

  const filename = `turn-os-pay-week-${input.weekStart}.pdf`;
  doc.save(filename);
  return filename;
}
