import type { FieldShellModel } from './types';

export const JUL28_SYNTHETIC_FIELD_SHELL: FieldShellModel = {
  context: {
    propertyName: 'Juniper House (Synthetic)',
    dateISO: '2026-07-28',
    dateLabel: 'Tuesday, July 28, 2026',
  },
  personalPlan: {
    now: {
      id: 'plan-602-paint-walk',
      unitNumber: '602',
      label: 'Paint inspection',
      trade: 'Paint',
      scope: ['Common', 'A', 'C', 'D'],
      warning: 'B: Restricted — do not enter',
    },
    next: {
      id: 'plan-603-clean-walk',
      unitNumber: '603',
      label: 'Clean inspection',
      trade: 'Clean',
      scope: ['C'],
    },
    backup: {
      id: 'plan-604-access-check',
      unitNumber: '604',
      label: 'Access check',
      scope: ['D'],
    },
  },
  assignedWork: [
    {
      id: 'assigned-602-paint',
      unitNumber: '602',
      scope: ['Common', 'A'],
      trade: 'Paint',
      detail: 'Personal assignment list shows Paint scope for today.',
      responsibleCrew: 'Atlas Paint (Synthetic)',
      destination: { workspace: 'unit-workspace', label: 'Unit 602 workspace' },
    },
    {
      id: 'assigned-603-clean',
      unitNumber: '603',
      scope: ['B', 'C'],
      trade: 'Clean',
      detail: 'Personal assignment list shows Clean scope for today.',
      responsibleCrew: 'Harbor Clean (Synthetic)',
      destination: { workspace: 'unit-workspace', label: 'Unit 603 workspace' },
    },
  ],
  progressingWork: [
    {
      id: 'progress-604-paint',
      unitNumber: '604',
      scope: ['C', 'D'],
      trade: 'Paint',
      detail: 'Crew reported work progressing; no inspection fact is recorded.',
      responsibleCrew: 'Bluebird Paint (Synthetic)',
      destination: { workspace: 'unit-workspace', label: 'Unit 604 workspace' },
    },
    {
      id: 'progress-1305-clean',
      unitNumber: '1305',
      scope: ['Common', 'A'],
      trade: 'Clean',
      detail: 'Crew reported work progressing; no inspection fact is recorded.',
      responsibleCrew: 'Harbor Clean (Synthetic)',
      destination: { workspace: 'unit-workspace', label: 'Unit 1305 workspace' },
    },
  ],
  needsMe: [
    {
      id: 'need-602-confirmation',
      category: 'needs-confirmation',
      unitNumber: '602',
      section: 'A',
      trade: 'Paint',
      whyLosIsNeeded: 'Captured wording and the personal assignment note do not match.',
      responsibleParty: 'Los',
      nextAction: 'Compare the source wording and confirm the personal note.',
      destination: { workspace: 'capture-review', label: 'Capture review — Unit 602' },
    },
    {
      id: 'need-603-inspection',
      category: 'needs-my-inspection',
      unitNumber: '603',
      section: 'C',
      trade: 'Clean',
      whyLosIsNeeded: 'Crew reported Clean complete; Los inspection is not recorded.',
      responsibleParty: 'Harbor Clean (Synthetic)',
      nextAction: 'Inspect Section C before preparing a property walk.',
      destination: { workspace: 'unit-workspace', label: 'Unit 603 workspace' },
    },
    {
      id: 'need-604-callback',
      category: 'callbacks',
      unitNumber: '604',
      section: 'Common',
      trade: 'Paint',
      whyLosIsNeeded: 'A personal callback note is waiting for reinspection.',
      responsibleParty: 'Atlas Paint (Synthetic)',
      nextAction: 'Walk the callback with the responsible crew.',
      destination: { workspace: 'unit-workspace', label: 'Unit 604 workspace' },
    },
    {
      id: 'need-1305-property-walk',
      category: 'property-walks',
      unitNumber: '1305',
      section: 'Common',
      trade: 'Clean',
      whyLosIsNeeded: 'The next scheduled property walkthrough needs route preparation.',
      responsibleParty: 'Los + property contact (Synthetic)',
      nextAction: 'Review personal inspection notes before 3:30 PM.',
      destination: { workspace: 'today', label: 'Today — 3:30 PM property walkthrough' },
    },
    {
      id: 'need-604-assignment-conflict',
      category: 'assignment-conflicts',
      unitNumber: '604',
      section: 'C',
      trade: 'Paint',
      whyLosIsNeeded: 'Two synthetic crew claims appear in the personal assignment notes.',
      responsibleParty: 'Los',
      nextAction: 'Compare assignment evidence without selecting a winner automatically.',
      destination: { workspace: 'turnboard', label: 'TurnBoard — Unit 604' },
    },
    {
      id: 'need-1305-access-blocker',
      category: 'access-blockers',
      unitNumber: '1305',
      section: 'B',
      trade: 'Clean',
      whyLosIsNeeded: 'Restricted access blocks the planned personal inspection.',
      responsibleParty: 'Property contact (Synthetic)',
      nextAction: 'Confirm the allowed access window before entry.',
      destination: { workspace: 'unit-workspace', label: 'Unit 1305 workspace' },
    },
    {
      id: 'need-603-maintenance-blocker',
      category: 'maintenance-blockers',
      unitNumber: '603',
      section: 'Common',
      trade: 'Paint',
      whyLosIsNeeded: 'A maintenance repair blocks the Paint inspection.',
      responsibleParty: 'Maintenance contact (Synthetic)',
      nextAction: 'Follow up after the repair is reported complete.',
      destination: { workspace: 'unit-workspace', label: 'Unit 603 workspace' },
    },
    {
      id: 'need-602-sync',
      category: 'save-or-sync-problems',
      unitNumber: '602',
      section: 'A',
      trade: 'Clean',
      whyLosIsNeeded: 'A synthetic capture is saved on this device and not synced.',
      responsibleParty: 'Los',
      nextAction: 'Review the saved capture and retry sync when connected.',
      destination: { workspace: 'sync-diagnostics', label: 'Sync & diagnostics — Unit 602 capture' },
    },
    {
      id: 'need-1305-paper',
      category: 'paper-reconciliation',
      unitNumber: '1305',
      section: 'C',
      trade: 'Paint',
      whyLosIsNeeded: 'Personal notes have not been compared with the authoritative paper TurnBoard.',
      responsibleParty: 'Los',
      nextAction: 'Compare the personal note with paper before end of day.',
      destination: { workspace: 'paper-reconciliation', label: 'Paper reconciliation — Unit 1305' },
    },
  ],
  nextPropertyWalk: {
    id: 'schedule-property-walk-1305',
    title: 'Next scheduled property walkthrough',
    timeLabel: '3:30 PM',
    unitNumber: '1305',
    detail: 'Meet the synthetic property contact at Unit 1305.',
    destination: { workspace: 'today', label: 'Today — 3:30 PM property walkthrough' },
  },
  endOfDayPaperReconciliation: {
    id: 'schedule-paper-reconciliation-1305',
    title: 'End-of-day paper reconciliation',
    timeLabel: '5:30 PM',
    unitNumber: '1305',
    detail: 'Compare personal notes with the authoritative paper TurnBoard.',
    destination: { workspace: 'paper-reconciliation', label: 'Paper reconciliation — Unit 1305' },
  },
  recentActivity: [
    {
      id: 'activity-604-progress',
      timeLabel: '1:42 PM',
      unitNumber: '604',
      summary: 'Saved a personal Paint progress note.',
      destination: { workspace: 'unit-workspace', label: 'Unit 604 workspace' },
    },
    {
      id: 'activity-602-device',
      timeLabel: '1:18 PM',
      unitNumber: '602',
      summary: 'Saved a synthetic capture on this device.',
      destination: { workspace: 'capture-review', label: 'Capture review — Unit 602' },
    },
  ],
  moreDestinations: [
    { id: 'crews', label: 'Crew / People', detail: 'Contacts and personal crew notes' },
    { id: 'reports', label: 'Reports', detail: 'Review your field summary' },
    { id: 'setup', label: 'Setup', detail: 'Property and app preferences' },
    { id: 'backup', label: 'Data & backup', detail: 'Export and device recovery' },
    { id: 'sync', label: 'Sync & diagnostics', detail: 'Local save and optional sync health' },
  ],
};
